{
  "109919 pytorch": {
    "FAILED": [],
    "FLAKY": [
      {
        "workflow_id": 6280706666,
        "id": 17058522048,
        "name": "linux-focal-rocm5.6-py3.8 / test (distributed, 1, 2, linux.rocm.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-09-23T03:51:30Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/6280706666/job/17058522048",
        "head_branch": "ciflow/periodic/109919",
        "pr_number": 109919,
        "head_sha": "9f2538f89d1b058e787c139dbc37025ea0c22054",
        "failure_captures": [
          "distributed/fsdp/test_fsdp_freezing_weights.py::TestFreezingWeights::test_freezing_weights_with_nested_trunk_False_freezing_method_FreezingMethod_GradToNone_freeze_after_wrap_fsdp_True"
        ],
        "failure_line": "FAILED [300.0706s] distributed/fsdp/test_fsdp_freezing_weights.py::TestFreezingWeights::test_freezing_weights_with_nested_trunk_False_freezing_method_FreezingMethod_GradToNone_freeze_after_wrap_fsdp_True - RuntimeError: Process 0 terminated or timed out after 300.05188751220703 seconds",
        "time": "2023-09-23T01:39:15.074773Z"
      }
    ],
    "BROKEN_TRUNK": [
      {
        "workflow_id": 6280706666,
        "id": 17058792764,
        "name": "win-vs2019-cuda11.8-py3 / test (default, 3, 4, windows.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-09-23T03:51:58Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/6280706666/job/17058792764",
        "head_branch": "ciflow/periodic/109919",
        "pr_number": 109919,
        "head_sha": "9f2538f89d1b058e787c139dbc37025ea0c22054",
        "failure_captures": [
          "C:/actions-runner/_work/pytorch/pytorch/build/win_tmp/build/torch/include\\torch/library.h(626): error C2872: 'std': ambiguous symbol"
        ],
        "failure_line": "C:/actions-runner/_work/pytorch/pytorch/build/win_tmp/build/torch/include\\torch/library.h(626): error C2872: 'std': ambiguous symbol",
        "time": "2023-09-23T02:03:02.990182Z"
      },
      {
        "workflow_id": 6280706666,
        "id": 17058792840,
        "name": "win-vs2019-cuda11.8-py3 / test (default, 4, 4, windows.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-09-23T03:37:10Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/6280706666/job/17058792840",
        "head_branch": "ciflow/periodic/109919",
        "pr_number": 109919,
        "head_sha": "9f2538f89d1b058e787c139dbc37025ea0c22054",
        "failure_captures": [
          "C:/actions-runner/_work/pytorch/pytorch/build/win_tmp/build/torch/include\\torch/library.h(626): error C2872: 'std': ambiguous symbol"
        ],
        "failure_line": "C:/actions-runner/_work/pytorch/pytorch/build/win_tmp/build/torch/include\\torch/library.h(626): error C2872: 'std': ambiguous symbol",
        "time": "2023-09-23T02:03:05.059828Z"
      }
    ],
    "UNSTABLE": [
      {
        "workflow_id": 6280706666,
        "id": 17058776714,
        "name": "linux-focal-cuda11.8-py3.9-gcc9 / test (multigpu, 1, 1, linux.g5.12xlarge.nvidia.gpu, unstable)",
        "conclusion": "failure",
        "completed_at": "2023-09-23T03:55:23Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/6280706666/job/17058776714",
        "head_branch": "ciflow/periodic/109919",
        "pr_number": 109919,
        "head_sha": "9f2538f89d1b058e787c139dbc37025ea0c22054",
        "failure_captures": [
          "distributed/fsdp/test_hsdp_dtensor_state_dict.py::TestHSDPWithDeviceMeshAndDTensor::test_hsdp_init_with_device_mesh"
        ],
        "failure_line": "FAILED [4.6621s] distributed/fsdp/test_hsdp_dtensor_state_dict.py::TestHSDPWithDeviceMeshAndDTensor::test_hsdp_init_with_device_mesh - RuntimeError: Process 3 exited with error code 10 and exception:",
        "time": "2023-09-23T02:01:24.389508Z"
      }
    ]
  },
  "90791 pytorch": {
    "FAILED": [
      {
        "workflow_id": 3714206650,
        "id": 10142872093,
        "name": "lintrunner",
        "conclusion": "failure",
        "completed_at": "2022-12-16T15:05:55Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/3714206650/jobs/6297806783",
        "head_branch": "gh/bdhirsh/356/head",
        "pr_number": 90791,
        "head_sha": "70711ab89515aa4515ce60d3c29a04dbdba8e06e",
        "failure_captures": [
          "Process completed with exit code 2."
        ],
        "failure_line": "##[error]Process completed with exit code 2.",
        "time": "2022-12-16T15:05:31.870000Z"
      },
      {
        "workflow_id": 3714206650,
        "id": 10142872329,
        "name": "Test tools",
        "conclusion": "failure",
        "completed_at": "2022-12-16T15:07:27Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/3714206650/jobs/6297806967",
        "head_branch": "gh/bdhirsh/356/head",
        "pr_number": 90791,
        "head_sha": "70711ab89515aa4515ce60d3c29a04dbdba8e06e",
        "failure_captures": [
          "Process completed with exit code 2."
        ],
        "failure_line": "##[error]Process completed with exit code 2.",
        "time": "2022-12-16T15:05:59.491000Z"
      }
    ],
    "FLAKY": [],
    "BROKEN_TRUNK": [],
    "UNSTABLE": []
  },
  "77700 pytorch": {
    "FAILED": [],
    "FLAKY": [],
    "BROKEN_TRUNK": [],
    "UNSTABLE": []
  },
  "76118 pytorch": {
    "FAILED": [],
    "FLAKY": [],
    "BROKEN_TRUNK": [],
    "UNSTABLE": []
  },
  "100652 pytorch": {
    "FAILED": [
      {
        "workflow_id": 5249183433,
        "id": 14204278817,
        "name": "cuda11.8-py3.10-gcc7-sm86 / test (inductor_timm, 2, 2, linux.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-06-12T23:39:10Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5249183433/jobs/9481967795",
        "head_branch": "ciflow/inductor/100652",
        "pr_number": 100652,
        "head_sha": "17a09e69c00f9416f8e9719a311d942df2b5fc42",
        "failure_captures": [
          "RuntimeError: CUDA error: uncorrectable ECC error encountered"
        ],
        "failure_line": "RuntimeError: CUDA error: uncorrectable ECC error encountered",
        "time": "2023-06-12T22:57:58.776004Z"
      }
    ],
    "FLAKY": [],
    "BROKEN_TRUNK": [
      {
        "workflow_id": 5249183433,
        "id": 14204279379,
        "name": "cuda11.8-py3.10-gcc7-sm86 / test (inductor_torchbench_dynamic, 1, 1, linux.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-06-12T23:52:57Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5249183433/jobs/9481968198",
        "head_branch": "ciflow/inductor/100652",
        "pr_number": 100652,
        "head_sha": "17a09e69c00f9416f8e9719a311d942df2b5fc42",
        "failure_captures": [
          "",
          "fail_to_run"
        ],
        "failure_line": "fail_to_run",
        "time": "2023-06-12T22:58:02.149643Z"
      },
      {
        "workflow_id": 5249183433,
        "id": 14204278909,
        "name": "cuda11.8-py3.10-gcc7-sm86 / test (inductor_torchbench, 1, 1, linux.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-06-13T00:34:02Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5249183433/jobs/9481967867",
        "head_branch": "ciflow/inductor/100652",
        "pr_number": 100652,
        "head_sha": "17a09e69c00f9416f8e9719a311d942df2b5fc42",
        "failure_captures": [
          "",
          "fail_to_run"
        ],
        "failure_line": "fail_to_run",
        "time": "2023-06-12T22:57:59.592338Z"
      },
      {
        "workflow_id": 5249183431,
        "id": 14204307666,
        "name": "cuda12.1-py3.10-gcc9-sm86-periodic-dynamo-benchmarks / test (aot_eager_torchbench, 1, 1, linux.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-06-13T00:06:07Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5249183431/jobs/9481990225",
        "head_branch": "ciflow/inductor/100652",
        "pr_number": 100652,
        "head_sha": "17a09e69c00f9416f8e9719a311d942df2b5fc42",
        "failure_captures": [
          "moco",
          "fail_to_run"
        ],
        "failure_line": "moco                               fail_to_run",
        "time": "2023-06-12T22:59:34.980746Z"
      },
      {
        "workflow_id": 5249183431,
        "id": 14204308144,
        "name": "cuda12.1-py3.10-gcc9-sm86-periodic-dynamo-benchmarks / test (dynamic_aot_eager_torchbench, 1, 1, linux.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-06-12T23:53:26Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5249183431/jobs/9481990597",
        "head_branch": "ciflow/inductor/100652",
        "pr_number": 100652,
        "head_sha": "17a09e69c00f9416f8e9719a311d942df2b5fc42",
        "failure_captures": [
          "moco",
          "fail_to_run"
        ],
        "failure_line": "moco                               fail_to_run",
        "time": "2023-06-12T22:59:35.761358Z"
      },
      {
        "workflow_id": 5249183431,
        "id": 14204307166,
        "name": "cuda12.1-py3.10-gcc9-sm86-periodic-dynamo-benchmarks / test (dynamo_eager_torchbench, 1, 1, linux.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-06-13T00:01:23Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5249183431/jobs/9481989829",
        "head_branch": "ciflow/inductor/100652",
        "pr_number": 100652,
        "head_sha": "17a09e69c00f9416f8e9719a311d942df2b5fc42",
        "failure_captures": [
          "moco",
          "fail_to_run"
        ],
        "failure_line": "moco                               fail_to_run",
        "time": "2023-06-12T22:59:33.478075Z"
      },
      {
        "workflow_id": 5249183433,
        "id": 14204082644,
        "name": "linux-focal-cpu-py3.8-gcc7-inductor / test (inductor_torchbench_cpu_accuracy, 1, 1, linux.4xlarge)",
        "conclusion": "failure",
        "completed_at": "2023-06-12T23:38:07Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5249183433/jobs/9481815573",
        "head_branch": "ciflow/inductor/100652",
        "pr_number": 100652,
        "head_sha": "17a09e69c00f9416f8e9719a311d942df2b5fc42",
        "failure_captures": [
          "sam",
          "fail_to_run"
        ],
        "failure_line": "sam                                fail_to_run",
        "time": "2023-06-12T22:45:44.981701Z"
      }
    ],
    "UNSTABLE": []
  },
  "91340 pytorch": {
    "FAILED": [],
    "FLAKY": [],
    "BROKEN_TRUNK": [],
    "UNSTABLE": []
  },
  "79694 pytorch": {
    "FAILED": [],
    "FLAKY": [],
    "BROKEN_TRUNK": [],
    "UNSTABLE": []
  },
  "100369 pytorch": {
    "FAILED": [
      {
        "workflow_id": 4912691700,
        "id": 13305922042,
        "name": "linux-bionic-py3_8-clang8-xla / test (xla, 1, 1, linux.4xlarge)",
        "conclusion": "failure",
        "completed_at": "2023-05-08T08:25:58Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/4912691700/jobs/8772243062",
        "head_branch": "update-xla-commit-hash/4849475010-42-1",
        "pr_number": 100369,
        "head_sha": "19603a570c078a92fdbce3e17fb8a14a17d6ada4",
        "failure_captures": [
          "FAILED: Build did NOT complete successfully"
        ],
        "failure_line": "FAILED: Build did NOT complete successfully",
        "time": "2023-05-08T07:55:56.352033Z"
      }
    ],
    "FLAKY": [],
    "BROKEN_TRUNK": [],
    "UNSTABLE": []
  },
  "92863 pytorch": {
    "FAILED": [
      {
        "workflow_id": 3991169410,
        "id": 10835558326,
        "name": "linux-focal-py3.7-gcc7 / test (distributed, 1, 2, linux.2xlarge)",
        "conclusion": "cancelled",
        "completed_at": "2023-01-24T02:48:29Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/3991169410/jobs/6845808750",
        "head_branch": "gh/soulitzer/173/head",
        "pr_number": 92863,
        "head_sha": "030a6d3fe98e46c82cdbae9b93a72ceab4febfd6",
        "failure_captures": [
          "##[error]The operation was canceled."
        ],
        "failure_line": "##[error]The operation was canceled.",
        "time": "2023-01-23T22:47:57.154000Z"
      }
    ],
    "FLAKY": [],
    "BROKEN_TRUNK": [
      {
        "workflow_id": 3991169410,
        "id": 10835645296,
        "name": "linux-bionic-py3_7-clang8-xla / test (xla, 1, 1, linux.4xlarge)",
        "conclusion": "failure",
        "completed_at": "2023-01-24T00:12:47Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/3991169410/jobs/6845872827",
        "head_branch": "gh/soulitzer/173/head",
        "pr_number": 92863,
        "head_sha": "030a6d3fe98e46c82cdbae9b93a72ceab4febfd6",
        "failure_captures": [
          "[  FAILED  ] AtenXlaTensorTest.TestFrobeniusNormInDims"
        ],
        "failure_line": "[  FAILED  ] AtenXlaTensorTest.TestFrobeniusNormInDims (2 ms)",
        "time": "2023-01-23T22:53:17.519000Z"
      }
    ],
    "UNSTABLE": []
  },
  "104214 pytorch": {
    "FAILED": [],
    "FLAKY": [],
    "BROKEN_TRUNK": [
      {
        "workflow_id": 5386107383,
        "id": 14578868938,
        "name": "linux-bionic-cuda12.1-py3.10-gcc9-sm86 / test (default, 3, 5, linux.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-06-27T06:25:16Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5386107383/jobs/9776474242",
        "head_branch": "malfet-patch-15",
        "pr_number": 104214,
        "head_sha": "dd52521aa51e4d609fb97b6a4cf657fc89c49308",
        "failure_captures": [
          "test_sparse_semi_structured.py::TestSparseSemiStructuredCUDA::test_mm_sparse_first_NT_cuda_int8"
        ],
        "failure_line": "FAILED [0.0133s] test_sparse_semi_structured.py::TestSparseSemiStructuredCUDA::test_mm_sparse_first_NT_cuda_int8 - AssertionError: \"_structured_sparse_linear\" does not match \"two_four_sgemm_cutlass_dispatch_layouts: Combination of row-majorand row-major layouts for input tensors is not supported\"",
        "time": "2023-06-27T06:15:51.054171Z"
      }
    ],
    "UNSTABLE": []
  },
  "105145 pytorch": {
    "FAILED": [],
    "FLAKY": [],
    "BROKEN_TRUNK": [
      {
        "workflow_id": 5546990040,
        "id": 15025544107,
        "name": "lintrunner / linux-job",
        "conclusion": "failure",
        "completed_at": "2023-07-13T19:39:44Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5546990040/jobs/10128289190",
        "head_branch": "gh/ezyang/2226/head",
        "pr_number": 105145,
        "head_sha": "bef28e5f9fe369ebf607ef6f4cc9bde84b0762e6",
        "failure_captures": [
          ">>> Lint for torch/_export/serde/upgrade.py:"
        ],
        "failure_line": ">>> Lint for torch/_export/serde/upgrade.py:",
        "time": "2023-07-13T19:26:27.842524Z"
      }
    ],
    "UNSTABLE": []
  },
  "107160 pytorch": {
    "FAILED": [],
    "FLAKY": [],
    "BROKEN_TRUNK": [
      {
        "workflow_id": 5859347753,
        "id": 15885841715,
        "name": "linux-bionic-cuda12.1-py3.10-gcc9-sm86 / test (default, 4, 5, linux.g5.4xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-08-14T19:50:09Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5859347753/job/15885841715",
        "head_branch": "gh/mrshenli/385/head",
        "pr_number": 107160,
        "head_sha": "1abba7bb35f1562329d0235dedf171790cd162a5",
        "failure_captures": [
          "inductor/test_torchinductor.py::TritonCodeGenTests::test_optimize_indexing_dtype_with_constraint"
        ],
        "failure_line": "FAILED [0.1966s] inductor/test_torchinductor.py::TritonCodeGenTests::test_optimize_indexing_dtype_with_constraint - torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:",
        "time": "2023-08-14T19:00:56.524425Z"
      }
    ],
    "UNSTABLE": [
      {
        "workflow_id": 5860028213,
        "id": 15887855756,
        "name": "linux-focal-rocm5.6-py3.8 / test (default, 1, 3, linux.rocm.gpu, unstable)",
        "conclusion": "failure",
        "completed_at": "2023-08-14T22:04:13Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5860028213/job/15887855756",
        "head_branch": "ciflow/trunk/107160",
        "pr_number": 107160,
        "head_sha": "1abba7bb35f1562329d0235dedf171790cd162a5",
        "failure_captures": [
          "inductor/test_torchinductor_opinfo.py::TestInductorOpInfoCUDA::test_comprehensive_tanh_cuda_float16"
        ],
        "failure_line": "FAILED [0.0914s] inductor/test_torchinductor_opinfo.py::TestInductorOpInfoCUDA::test_comprehensive_tanh_cuda_float16",
        "time": "2023-08-14T20:14:59.760637Z"
      },
      {
        "workflow_id": 5860028213,
        "id": 15887855946,
        "name": "linux-focal-rocm5.6-py3.8 / test (default, 2, 3, linux.rocm.gpu, unstable)",
        "conclusion": "failure",
        "completed_at": "2023-08-14T22:10:08Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5860028213/job/15887855946",
        "head_branch": "ciflow/trunk/107160",
        "pr_number": 107160,
        "head_sha": "1abba7bb35f1562329d0235dedf171790cd162a5",
        "failure_captures": [
          "profiler/test_profiler.py::TestProfiler::test_kineto_profiler_with_environment_variable"
        ],
        "failure_line": "FAILED [6.9686s] profiler/test_profiler.py::TestProfiler::test_kineto_profiler_with_environment_variable - AssertionError: False is not true : Kineto is not working properly with the Dynolog environment variable",
        "time": "2023-08-14T20:15:00.814152Z"
      },
      {
        "workflow_id": 5860028213,
        "id": 15887856086,
        "name": "linux-focal-rocm5.6-py3.8 / test (default, 3, 3, linux.rocm.gpu, unstable)",
        "conclusion": "failure",
        "completed_at": "2023-08-14T23:02:38Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5860028213/job/15887856086",
        "head_branch": "ciflow/trunk/107160",
        "pr_number": 107160,
        "head_sha": "1abba7bb35f1562329d0235dedf171790cd162a5",
        "failure_captures": [
          "inductor/test_torchinductor_opinfo.py::TestInductorOpInfoCUDA::test_comprehensive_nn_functional_instance_norm_cuda_float32"
        ],
        "failure_line": "FAILED [0.6190s] inductor/test_torchinductor_opinfo.py::TestInductorOpInfoCUDA::test_comprehensive_nn_functional_instance_norm_cuda_float32",
        "time": "2023-08-14T20:15:00.976758Z"
      }
    ]
  },
  "105998 pytorch": {
    "FAILED": [],
    "FLAKY": [],
    "BROKEN_TRUNK": [],
    "UNSTABLE": []
  },
  "104312 pytorch": {
    "FAILED": [],
    "FLAKY": [],
    "BROKEN_TRUNK": [],
    "UNSTABLE": [
      {
        "workflow_id": 5395930989,
        "id": 14611204945,
        "name": "linux-bionic-cuda12.1-py3.10-gcc9-bazel-test / build-and-test (default, 1, 1, linux.4xlarge.nvidia.gpu, unstable)",
        "conclusion": "failure",
        "completed_at": "2023-06-28T04:11:53Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/5395930989/jobs/9801455548",
        "head_branch": "malfet/be-fix-override-and-pass-by-value",
        "pr_number": 104312,
        "head_sha": "d4f67cbf8b98d7b27b6c12f278af9e281e147bd5",
        "failure_captures": [
          "FAILED: Build did NOT complete successfully"
        ],
        "failure_line": "FAILED: Build did NOT complete successfully (87 packages loaded, 2396 targets configured)",
        "time": "2023-06-28T04:03:25.058757Z"
      }
    ]
  },
  "109750 pytorch": {
    "FAILED": [],
    "FLAKY": [
      {
        "workflow_id": 6254944836,
        "id": 16985650612,
        "name": "linux-focal-cuda11.8-py3.10-gcc9 / test (distributed, 1, 3, linux.8xlarge.nvidia.gpu)",
        "conclusion": "failure",
        "completed_at": "2023-09-21T01:07:19Z",
        "html_url": "https://github.com/pytorch/pytorch/actions/runs/6254944836/job/16985650612",
        "head_branch": "gh/eellison/544/head",
        "pr_number": 109750,
        "head_sha": "6cc5e37592d370a449dac076cf7976bde18238bf",
        "failure_captures": [
          "RuntimeError: distributed/test_store 1/1 failed"
        ],
        "failure_line": "RuntimeError: distributed/test_store 1/1 failed! Received signal: SIGIOT",
        "time": "2023-09-21T00:54:52.471611Z"
      }
    ],
    "BROKEN_TRUNK": [],
    "UNSTABLE": []
  }
}
